# Generated by Django 4.2.30 on 2026-04-23 17:15

import django.core.validators
from django.db import migrations, models
import profiles.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=profiles.utils.uuid7, editable=False, help_text='UUID v7 primary key (time-based, sortable)', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Full name (stored lowercase for consistency)', max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_index=True, help_text='Gender: male or female', max_length=10)),
                ('gender_probability', models.FloatField(help_text='Confidence score for gender (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('age', models.IntegerField(db_index=True, help_text='Exact age in years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('age_group', models.CharField(choices=[('child', 'Child (0-12)'), ('teenager', 'Teenager (13-19)'), ('adult', 'Adult (20-64)'), ('senior', 'Senior (65+)')], db_index=True, help_text='Age group classification', max_length=20)),
                ('country_id', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code (e.g., NG, KE, GH)', max_length=2)),
                ('country_name', models.CharField(help_text='Full country name', max_length=100)),
                ('country_probability', models.FloatField(help_text='Confidence score for country (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC)')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gender', 'created_at'], name='profiles_pr_gender_3ce792_idx'), models.Index(fields=['age_group', 'age'], name='profiles_pr_age_gro_f6fa14_idx'), models.Index(fields=['country_id', 'created_at'], name='profiles_pr_country_338996_idx'), models.Index(fields=['gender', 'country_id'], name='profiles_pr_gender_7ed43e_idx'), models.Index(fields=['age_group', 'country_id'], name='profiles_pr_age_gro_bb4888_idx')],
            },
        ),
    ]
